/*
[
  {
    "login": "rafaelsachetto",
    "id": 42780
  },
  {
    "login": "rafaelsachetto",
    "id": 42780
  }
]

{
  "login": ["defunkt", 1],
  "id": 2,
  "avatar_url": "https://avatars.githubusercontent.com/u/2?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/defunkt",
  "html_url": "https://github.com/defunkt",
  "followers_url": "https://api.github.com/users/defunkt/followers",
  "following_url": "https://api.github.com/users/defunkt/following{/other_user}",
  "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
  "organizations_url": "https://api.github.com/users/defunkt/orgs",
  "repos_url": "https://api.github.com/users/defunkt/repos",
  "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
  "received_events_url": "https://api.github.com/users/defunkt/received_events",
  "type": "User",
  "site_admin": true,
  "name": "Chris Wanstrath",
  "company": "GitHub",
  "blog": "http://chriswanstrath.com/",
  "location": "San Francisco",
  "email": "chris@github.com",
  "hireable": true,
  "bio": null,
  "public_repos": 108,
  "public_gists": 280,
  "followers": 14509,
  "following": 208,
  "created_at": "2007-10-20T05:24:19Z",
  "updated_at": "2015-08-03T18:05:52Z"
}

// console.table
[
  {
    "login": "rafaelsachetto",
    "id": 42780,
    "avatar_url": "https://avatars.githubusercontent.com/u/42780?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rafaelsachetto",
    "html_url": "https://github.com/rafaelsachetto",
    "followers_url": "https://api.github.com/users/rafaelsachetto/followers",
    "following_url": "https://api.github.com/users/rafaelsachetto/following{/other_user}",
    "gists_url": "https://api.github.com/users/rafaelsachetto/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rafaelsachetto/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rafaelsachetto/subscriptions",
    "organizations_url": "https://api.github.com/users/rafaelsachetto/orgs",
    "repos_url": "https://api.github.com/users/rafaelsachetto/repos",
    "events_url": "https://api.github.com/users/rafaelsachetto/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rafaelsachetto/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tsnow",
    "id": 48890,
    "avatar_url": "https://avatars.githubusercontent.com/u/48890?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tsnow",
    "html_url": "https://github.com/tsnow",
    "followers_url": "https://api.github.com/users/tsnow/followers",
    "following_url": "https://api.github.com/users/tsnow/following{/other_user}",
    "gists_url": "https://api.github.com/users/tsnow/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tsnow/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tsnow/subscriptions",
    "organizations_url": "https://api.github.com/users/tsnow/orgs",
    "repos_url": "https://api.github.com/users/tsnow/repos",
    "events_url": "https://api.github.com/users/tsnow/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tsnow/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Sup3rgnu",
    "id": 67664,
    "avatar_url": "https://avatars.githubusercontent.com/u/67664?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Sup3rgnu",
    "html_url": "https://github.com/Sup3rgnu",
    "followers_url": "https://api.github.com/users/Sup3rgnu/followers",
    "following_url": "https://api.github.com/users/Sup3rgnu/following{/other_user}",
    "gists_url": "https://api.github.com/users/Sup3rgnu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Sup3rgnu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Sup3rgnu/subscriptions",
    "organizations_url": "https://api.github.com/users/Sup3rgnu/orgs",
    "repos_url": "https://api.github.com/users/Sup3rgnu/repos",
    "events_url": "https://api.github.com/users/Sup3rgnu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Sup3rgnu/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tokuda109",
    "id": 108762,
    "avatar_url": "https://avatars.githubusercontent.com/u/108762?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tokuda109",
    "html_url": "https://github.com/tokuda109",
    "followers_url": "https://api.github.com/users/tokuda109/followers",
    "following_url": "https://api.github.com/users/tokuda109/following{/other_user}",
    "gists_url": "https://api.github.com/users/tokuda109/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tokuda109/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tokuda109/subscriptions",
    "organizations_url": "https://api.github.com/users/tokuda109/orgs",
    "repos_url": "https://api.github.com/users/tokuda109/repos",
    "events_url": "https://api.github.com/users/tokuda109/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tokuda109/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "svallory",
    "id": 117560,
    "avatar_url": "https://avatars.githubusercontent.com/u/117560?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/svallory",
    "html_url": "https://github.com/svallory",
    "followers_url": "https://api.github.com/users/svallory/followers",
    "following_url": "https://api.github.com/users/svallory/following{/other_user}",
    "gists_url": "https://api.github.com/users/svallory/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/svallory/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/svallory/subscriptions",
    "organizations_url": "https://api.github.com/users/svallory/orgs",
    "repos_url": "https://api.github.com/users/svallory/repos",
    "events_url": "https://api.github.com/users/svallory/events{/privacy}",
    "received_events_url": "https://api.github.com/users/svallory/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "douglascamata",
    "id": 159076,
    "avatar_url": "https://avatars.githubusercontent.com/u/159076?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/douglascamata",
    "html_url": "https://github.com/douglascamata",
    "followers_url": "https://api.github.com/users/douglascamata/followers",
    "following_url": "https://api.github.com/users/douglascamata/following{/other_user}",
    "gists_url": "https://api.github.com/users/douglascamata/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/douglascamata/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/douglascamata/subscriptions",
    "organizations_url": "https://api.github.com/users/douglascamata/orgs",
    "repos_url": "https://api.github.com/users/douglascamata/repos",
    "events_url": "https://api.github.com/users/douglascamata/events{/privacy}",
    "received_events_url": "https://api.github.com/users/douglascamata/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ksauzz",
    "id": 451586,
    "avatar_url": "https://avatars.githubusercontent.com/u/451586?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ksauzz",
    "html_url": "https://github.com/ksauzz",
    "followers_url": "https://api.github.com/users/ksauzz/followers",
    "following_url": "https://api.github.com/users/ksauzz/following{/other_user}",
    "gists_url": "https://api.github.com/users/ksauzz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ksauzz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ksauzz/subscriptions",
    "organizations_url": "https://api.github.com/users/ksauzz/orgs",
    "repos_url": "https://api.github.com/users/ksauzz/repos",
    "events_url": "https://api.github.com/users/ksauzz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ksauzz/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tommi-lew",
    "id": 827889,
    "avatar_url": "https://avatars.githubusercontent.com/u/827889?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tommi-lew",
    "html_url": "https://github.com/tommi-lew",
    "followers_url": "https://api.github.com/users/tommi-lew/followers",
    "following_url": "https://api.github.com/users/tommi-lew/following{/other_user}",
    "gists_url": "https://api.github.com/users/tommi-lew/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tommi-lew/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tommi-lew/subscriptions",
    "organizations_url": "https://api.github.com/users/tommi-lew/orgs",
    "repos_url": "https://api.github.com/users/tommi-lew/repos",
    "events_url": "https://api.github.com/users/tommi-lew/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tommi-lew/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "eranb",
    "id": 942095,
    "avatar_url": "https://avatars.githubusercontent.com/u/942095?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/eranb",
    "html_url": "https://github.com/eranb",
    "followers_url": "https://api.github.com/users/eranb/followers",
    "following_url": "https://api.github.com/users/eranb/following{/other_user}",
    "gists_url": "https://api.github.com/users/eranb/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/eranb/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/eranb/subscriptions",
    "organizations_url": "https://api.github.com/users/eranb/orgs",
    "repos_url": "https://api.github.com/users/eranb/repos",
    "events_url": "https://api.github.com/users/eranb/events{/privacy}",
    "received_events_url": "https://api.github.com/users/eranb/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "savekirk",
    "id": 1415994,
    "avatar_url": "https://avatars.githubusercontent.com/u/1415994?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/savekirk",
    "html_url": "https://github.com/savekirk",
    "followers_url": "https://api.github.com/users/savekirk/followers",
    "following_url": "https://api.github.com/users/savekirk/following{/other_user}",
    "gists_url": "https://api.github.com/users/savekirk/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/savekirk/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/savekirk/subscriptions",
    "organizations_url": "https://api.github.com/users/savekirk/orgs",
    "repos_url": "https://api.github.com/users/savekirk/repos",
    "events_url": "https://api.github.com/users/savekirk/events{/privacy}",
    "received_events_url": "https://api.github.com/users/savekirk/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mzaragoza",
    "id": 1479619,
    "avatar_url": "https://avatars.githubusercontent.com/u/1479619?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mzaragoza",
    "html_url": "https://github.com/mzaragoza",
    "followers_url": "https://api.github.com/users/mzaragoza/followers",
    "following_url": "https://api.github.com/users/mzaragoza/following{/other_user}",
    "gists_url": "https://api.github.com/users/mzaragoza/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mzaragoza/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mzaragoza/subscriptions",
    "organizations_url": "https://api.github.com/users/mzaragoza/orgs",
    "repos_url": "https://api.github.com/users/mzaragoza/repos",
    "events_url": "https://api.github.com/users/mzaragoza/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mzaragoza/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "zhuyinan",
    "id": 1510656,
    "avatar_url": "https://avatars.githubusercontent.com/u/1510656?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zhuyinan",
    "html_url": "https://github.com/zhuyinan",
    "followers_url": "https://api.github.com/users/zhuyinan/followers",
    "following_url": "https://api.github.com/users/zhuyinan/following{/other_user}",
    "gists_url": "https://api.github.com/users/zhuyinan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zhuyinan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zhuyinan/subscriptions",
    "organizations_url": "https://api.github.com/users/zhuyinan/orgs",
    "repos_url": "https://api.github.com/users/zhuyinan/repos",
    "events_url": "https://api.github.com/users/zhuyinan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zhuyinan/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "showaid",
    "id": 1582582,
    "avatar_url": "https://avatars.githubusercontent.com/u/1582582?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/showaid",
    "html_url": "https://github.com/showaid",
    "followers_url": "https://api.github.com/users/showaid/followers",
    "following_url": "https://api.github.com/users/showaid/following{/other_user}",
    "gists_url": "https://api.github.com/users/showaid/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/showaid/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/showaid/subscriptions",
    "organizations_url": "https://api.github.com/users/showaid/orgs",
    "repos_url": "https://api.github.com/users/showaid/repos",
    "events_url": "https://api.github.com/users/showaid/events{/privacy}",
    "received_events_url": "https://api.github.com/users/showaid/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ziyasal",
    "id": 1651945,
    "avatar_url": "https://avatars.githubusercontent.com/u/1651945?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ziyasal",
    "html_url": "https://github.com/ziyasal",
    "followers_url": "https://api.github.com/users/ziyasal/followers",
    "following_url": "https://api.github.com/users/ziyasal/following{/other_user}",
    "gists_url": "https://api.github.com/users/ziyasal/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ziyasal/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ziyasal/subscriptions",
    "organizations_url": "https://api.github.com/users/ziyasal/orgs",
    "repos_url": "https://api.github.com/users/ziyasal/repos",
    "events_url": "https://api.github.com/users/ziyasal/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ziyasal/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "luoyangylh",
    "id": 1758102,
    "avatar_url": "https://avatars.githubusercontent.com/u/1758102?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/luoyangylh",
    "html_url": "https://github.com/luoyangylh",
    "followers_url": "https://api.github.com/users/luoyangylh/followers",
    "following_url": "https://api.github.com/users/luoyangylh/following{/other_user}",
    "gists_url": "https://api.github.com/users/luoyangylh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/luoyangylh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/luoyangylh/subscriptions",
    "organizations_url": "https://api.github.com/users/luoyangylh/orgs",
    "repos_url": "https://api.github.com/users/luoyangylh/repos",
    "events_url": "https://api.github.com/users/luoyangylh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/luoyangylh/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "robot9",
    "id": 1811913,
    "avatar_url": "https://avatars.githubusercontent.com/u/1811913?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/robot9",
    "html_url": "https://github.com/robot9",
    "followers_url": "https://api.github.com/users/robot9/followers",
    "following_url": "https://api.github.com/users/robot9/following{/other_user}",
    "gists_url": "https://api.github.com/users/robot9/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/robot9/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/robot9/subscriptions",
    "organizations_url": "https://api.github.com/users/robot9/orgs",
    "repos_url": "https://api.github.com/users/robot9/repos",
    "events_url": "https://api.github.com/users/robot9/events{/privacy}",
    "received_events_url": "https://api.github.com/users/robot9/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "srned",
    "id": 1821757,
    "avatar_url": "https://avatars.githubusercontent.com/u/1821757?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/srned",
    "html_url": "https://github.com/srned",
    "followers_url": "https://api.github.com/users/srned/followers",
    "following_url": "https://api.github.com/users/srned/following{/other_user}",
    "gists_url": "https://api.github.com/users/srned/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/srned/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/srned/subscriptions",
    "organizations_url": "https://api.github.com/users/srned/orgs",
    "repos_url": "https://api.github.com/users/srned/repos",
    "events_url": "https://api.github.com/users/srned/events{/privacy}",
    "received_events_url": "https://api.github.com/users/srned/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "sanyer",
    "id": 1888892,
    "avatar_url": "https://avatars.githubusercontent.com/u/1888892?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sanyer",
    "html_url": "https://github.com/sanyer",
    "followers_url": "https://api.github.com/users/sanyer/followers",
    "following_url": "https://api.github.com/users/sanyer/following{/other_user}",
    "gists_url": "https://api.github.com/users/sanyer/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sanyer/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sanyer/subscriptions",
    "organizations_url": "https://api.github.com/users/sanyer/orgs",
    "repos_url": "https://api.github.com/users/sanyer/repos",
    "events_url": "https://api.github.com/users/sanyer/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sanyer/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "birgita",
    "id": 1894149,
    "avatar_url": "https://avatars.githubusercontent.com/u/1894149?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/birgita",
    "html_url": "https://github.com/birgita",
    "followers_url": "https://api.github.com/users/birgita/followers",
    "following_url": "https://api.github.com/users/birgita/following{/other_user}",
    "gists_url": "https://api.github.com/users/birgita/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/birgita/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/birgita/subscriptions",
    "organizations_url": "https://api.github.com/users/birgita/orgs",
    "repos_url": "https://api.github.com/users/birgita/repos",
    "events_url": "https://api.github.com/users/birgita/events{/privacy}",
    "received_events_url": "https://api.github.com/users/birgita/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rmmillar86",
    "id": 1894426,
    "avatar_url": "https://avatars.githubusercontent.com/u/1894426?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rmmillar86",
    "html_url": "https://github.com/rmmillar86",
    "followers_url": "https://api.github.com/users/rmmillar86/followers",
    "following_url": "https://api.github.com/users/rmmillar86/following{/other_user}",
    "gists_url": "https://api.github.com/users/rmmillar86/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rmmillar86/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rmmillar86/subscriptions",
    "organizations_url": "https://api.github.com/users/rmmillar86/orgs",
    "repos_url": "https://api.github.com/users/rmmillar86/repos",
    "events_url": "https://api.github.com/users/rmmillar86/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rmmillar86/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "yoshi10321",
    "id": 1895209,
    "avatar_url": "https://avatars.githubusercontent.com/u/1895209?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yoshi10321",
    "html_url": "https://github.com/yoshi10321",
    "followers_url": "https://api.github.com/users/yoshi10321/followers",
    "following_url": "https://api.github.com/users/yoshi10321/following{/other_user}",
    "gists_url": "https://api.github.com/users/yoshi10321/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yoshi10321/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yoshi10321/subscriptions",
    "organizations_url": "https://api.github.com/users/yoshi10321/orgs",
    "repos_url": "https://api.github.com/users/yoshi10321/repos",
    "events_url": "https://api.github.com/users/yoshi10321/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yoshi10321/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "shilezi",
    "id": 1895283,
    "avatar_url": "https://avatars.githubusercontent.com/u/1895283?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/shilezi",
    "html_url": "https://github.com/shilezi",
    "followers_url": "https://api.github.com/users/shilezi/followers",
    "following_url": "https://api.github.com/users/shilezi/following{/other_user}",
    "gists_url": "https://api.github.com/users/shilezi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/shilezi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/shilezi/subscriptions",
    "organizations_url": "https://api.github.com/users/shilezi/orgs",
    "repos_url": "https://api.github.com/users/shilezi/repos",
    "events_url": "https://api.github.com/users/shilezi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/shilezi/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jessebikman",
    "id": 1895382,
    "avatar_url": "https://avatars.githubusercontent.com/u/1895382?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jessebikman",
    "html_url": "https://github.com/jessebikman",
    "followers_url": "https://api.github.com/users/jessebikman/followers",
    "following_url": "https://api.github.com/users/jessebikman/following{/other_user}",
    "gists_url": "https://api.github.com/users/jessebikman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jessebikman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jessebikman/subscriptions",
    "organizations_url": "https://api.github.com/users/jessebikman/orgs",
    "repos_url": "https://api.github.com/users/jessebikman/repos",
    "events_url": "https://api.github.com/users/jessebikman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jessebikman/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "turboho",
    "id": 1897173,
    "avatar_url": "https://avatars.githubusercontent.com/u/1897173?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/turboho",
    "html_url": "https://github.com/turboho",
    "followers_url": "https://api.github.com/users/turboho/followers",
    "following_url": "https://api.github.com/users/turboho/following{/other_user}",
    "gists_url": "https://api.github.com/users/turboho/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/turboho/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/turboho/subscriptions",
    "organizations_url": "https://api.github.com/users/turboho/orgs",
    "repos_url": "https://api.github.com/users/turboho/repos",
    "events_url": "https://api.github.com/users/turboho/events{/privacy}",
    "received_events_url": "https://api.github.com/users/turboho/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "yekowele",
    "id": 1898382,
    "avatar_url": "https://avatars.githubusercontent.com/u/1898382?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yekowele",
    "html_url": "https://github.com/yekowele",
    "followers_url": "https://api.github.com/users/yekowele/followers",
    "following_url": "https://api.github.com/users/yekowele/following{/other_user}",
    "gists_url": "https://api.github.com/users/yekowele/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yekowele/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yekowele/subscriptions",
    "organizations_url": "https://api.github.com/users/yekowele/orgs",
    "repos_url": "https://api.github.com/users/yekowele/repos",
    "events_url": "https://api.github.com/users/yekowele/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yekowele/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "johnnywell",
    "id": 1902036,
    "avatar_url": "https://avatars.githubusercontent.com/u/1902036?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/johnnywell",
    "html_url": "https://github.com/johnnywell",
    "followers_url": "https://api.github.com/users/johnnywell/followers",
    "following_url": "https://api.github.com/users/johnnywell/following{/other_user}",
    "gists_url": "https://api.github.com/users/johnnywell/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/johnnywell/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/johnnywell/subscriptions",
    "organizations_url": "https://api.github.com/users/johnnywell/orgs",
    "repos_url": "https://api.github.com/users/johnnywell/repos",
    "events_url": "https://api.github.com/users/johnnywell/events{/privacy}",
    "received_events_url": "https://api.github.com/users/johnnywell/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "potentialcoder",
    "id": 1902154,
    "avatar_url": "https://avatars.githubusercontent.com/u/1902154?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/potentialcoder",
    "html_url": "https://github.com/potentialcoder",
    "followers_url": "https://api.github.com/users/potentialcoder/followers",
    "following_url": "https://api.github.com/users/potentialcoder/following{/other_user}",
    "gists_url": "https://api.github.com/users/potentialcoder/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/potentialcoder/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/potentialcoder/subscriptions",
    "organizations_url": "https://api.github.com/users/potentialcoder/orgs",
    "repos_url": "https://api.github.com/users/potentialcoder/repos",
    "events_url": "https://api.github.com/users/potentialcoder/events{/privacy}",
    "received_events_url": "https://api.github.com/users/potentialcoder/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "matthewmspencer",
    "id": 1902852,
    "avatar_url": "https://avatars.githubusercontent.com/u/1902852?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/matthewmspencer",
    "html_url": "https://github.com/matthewmspencer",
    "followers_url": "https://api.github.com/users/matthewmspencer/followers",
    "following_url": "https://api.github.com/users/matthewmspencer/following{/other_user}",
    "gists_url": "https://api.github.com/users/matthewmspencer/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/matthewmspencer/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/matthewmspencer/subscriptions",
    "organizations_url": "https://api.github.com/users/matthewmspencer/orgs",
    "repos_url": "https://api.github.com/users/matthewmspencer/repos",
    "events_url": "https://api.github.com/users/matthewmspencer/events{/privacy}",
    "received_events_url": "https://api.github.com/users/matthewmspencer/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mojombo",
    "id": 1,
    "avatar_url": "https://avatars.githubusercontent.com/u/1?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mojombo",
    "html_url": "https://github.com/mojombo",
    "followers_url": "https://api.github.com/users/mojombo/followers",
    "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
    "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
    "organizations_url": "https://api.github.com/users/mojombo/orgs",
    "repos_url": "https://api.github.com/users/mojombo/repos",
    "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mojombo/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pjhyett",
    "id": 3,
    "avatar_url": "https://avatars.githubusercontent.com/u/3?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pjhyett",
    "html_url": "https://github.com/pjhyett",
    "followers_url": "https://api.github.com/users/pjhyett/followers",
    "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
    "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
    "organizations_url": "https://api.github.com/users/pjhyett/orgs",
    "repos_url": "https://api.github.com/users/pjhyett/repos",
    "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pjhyett/received_events",
    "type": "User",
    "site_admin": true
  }
]
*/
